### ISSUE TITLE
New palette for Spyder's UI

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/ux-improvements#13]
We need a new palette for Spyder's interface with new shades of blue and grey that work well together:

To keep:
-Dark blue from background
-Dark grey for most UI elements
-White for text and some icons

To change:
-Blue of selections/hover (Opacity or light grey)
-Blue in the help pane start page 
-Blue tiny lines in the pane tabs
-Tooltips #2 
-Blue in titles of help pane 
-Green in help pane 
Theme for help pane: https://bootswatch.com/darkly/

**Comment by isabela-pf** [comment]
I’ve been working a lot in the background trying to get this right so we can unblock some of other issues on this repo, but so far this has taken more experiments than I anticipated. Thanks for your patience.

A little review on the goals of creating a Spyder color system:
- Bring greater consistency to the UI for a better user experience
- Consolidate the many colors currently spread out in Spyder’s code base
- Create a formalized system of names to identify colors based on their use
- Provide a reference for people working on Spyder to know what is being used and what they should use
- Provide a range of color that provides lots of options for colors to be used together with [accessible contrast ratios](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html).
- Adjust existing colors to help them align better with the rest of the palette and have more options to be used accessibly

This isn’t quite done, but this is the direction I’m working on refining for dark mode. It’s a combination of ideas from the current (v4.1.5) UI’s colors, the [Darkly](https://bootswatch.com/darkly/) palette’s hue and temperature, and [Material Design’s](https://material.io/design/color/the-color-system.html) value distribution. Since this is long and needs refinement, I can type out all the colors in the next round.

<img width="852" alt="0-9" src="https://user-images.githubusercontent.com/50221806/94975184-b95ed380-04c5-11eb-962c-dad9582eb0b7.png">

Here is how this might look in the UI. I’m showing it old mockups (because I already had them available to be recolored), so don’t worry about that part.

<img width="559" alt="0-9 Test-2" src="https://user-images.githubusercontent.com/50221806/94975217-d4c9de80-04c5-11eb-8784-69fedd830d8a.png">
<img width="550" alt="0-9 Test" src="https://user-images.githubusercontent.com/50221806/94975227-d85d6580-04c5-11eb-93e2-dc9320b3cc13.png">
<img width="499" alt="0-9 Test-1" src="https://user-images.githubusercontent.com/50221806/94975230-dd221980-04c5-11eb-9883-d68f2e6f5c74.png">

What needs to be reviewed:
- Colors (Does it look close to current Spyder? Does any part stand out? Are colors missing?)
- Categories they are grouped by
- Naming
- Anything that seems to be missing

Even though I’m starting my design with dark mode (since it is the default), I’m intentionally creating a color system that allows dark and light mode to reflect each other. What does that mean, though? This is the current scale of overall grey I’m experimenting with:

<img width="469" alt="ultima2" src="https://user-images.githubusercontent.com/50221806/94975564-f1b2e180-04c6-11eb-9a30-bc92469ddcde.png">

From this, I pull the dark mode base from the dark half of the scale and all dark mode accents (like text) from the opposite half. Light mode should just flip it. The main edits will come in play on the accent and info colors to make sure they have enough contrast to be used on the background colors.

With this color palette, I also think it is worth editing Spyder’s color icons to match the relevant colors we end up choosing.

**Comment by isabela-pf** [comment]
As promised, I've narrowed down the number of colors proposed for use in each section. It's still based on a larger color scale (updated color names now reflect that), but helps make the choice of what color to use where in the UI a little easier. 

Meeting with some Spyder team members identified a few more areas of color I need to include next round, but I still wanted to update here with the more accurate version as I start testing it in the UI and with early contrast review.

List of colors:

<img width="852" alt="0-13" src="https://user-images.githubusercontent.com/50221806/95301975-2a8be700-0836-11eb-9d5c-d75c86f774d2.png">

How it might look in the UI:

<img width="559" alt="0-13 Test-2" src="https://user-images.githubusercontent.com/50221806/95302003-337cb880-0836-11eb-9974-c1572cc5adf4.png">

<img width="550" alt="0-13 Test" src="https://user-images.githubusercontent.com/50221806/95302018-37a8d600-0836-11eb-9210-6d2b59149c89.png">

<img width="499" alt="0-13 Test-1" src="https://user-images.githubusercontent.com/50221806/95302031-3a0b3000-0836-11eb-8974-dd53895603ca.png">

**Comment by isabela-pf** [comment]
I'm back with another revision of colors. This version is more refined and complete since I looped in the work for colors to differentiate groups of info in Spyder (like the Variable Explorer #7). I also added a color option to the Background and Text sets since experimenting with them and comparing them to colors currently used in Spyder showed they were missing a pre-existing value. Broken down for easier access and documentation, here's the proposed colors for dark mode:

### Background Colors
These are the colors that make up the majority of the Spyder UI since they are used to define the different sections of Spyder. All other elements colors rest on these.
<img width="850" alt="2-14background" src="https://user-images.githubusercontent.com/50221806/95832155-c9a95680-0cee-11eb-9417-3119491e14d6.png">
Background color 1 `#19232D`
Background color 2 `#262E38`
Background color 3 `#455364`
Background color 4 `#60798B`
Background color 5 `#9DA9B5`

### Text Colors
Text in Spyder should be in one of these colors. Remember to be cautious of color contrast; as the number for the background color and text color get larger, the color scale converges (Background color 5 and Text color 5 are the same) and those colors should not be used together.
<img width="852" alt="2-14text" src="https://user-images.githubusercontent.com/50221806/95832736-8e5b5780-0cef-11eb-9c81-54a340c8c5db.png">
Text color 1 `#FFFFFF`
Text color 2 `#FAFAFA`
Text color 3 `#EEEEEE`
Text color 4 `#D9D8D8`
Text color 5 `#9DA9B5`

### Accent Colors
Used for highlighting areas of Spyder, usually areas that are selected or are being interacted with. To avoid splitting user focus, apply accent colors thoughtfully and sparingly.
<img width="852" alt="2-14accent" src="https://user-images.githubusercontent.com/50221806/95833282-3f61f200-0cf0-11eb-8a85-a68044cc5fdf.png">
Accent color 1 `#3775A9`
Accent color 2 `#62BFFD`
Accent color 3 `#DAF0FF`

### Info Colors
These colors reinforce feedback or roles of parts of Spyder. They are also used sparingly.
<img width="850" alt="2-14info" src="https://user-images.githubusercontent.com/50221806/95833731-e777bb00-0cf0-11eb-9061-d838212d2d1e.png">
Success colors represent a completed action or starting an action (like play icons).
Success color 1 `#0A8B65`
Success color 2 `#20C997`
Success color 3 `#B0F5E1`

Error colors represent errors or stopping an action.
Error color 1 `#BD1200`
Error color 2 `#E74C3C`
Error color 3 `#FFC3BD`

Warn colors report potential problems. They tend to be used the least.
Warn color 1 `#DE6B2B`
Warn color 2 `#F39C12`
Warn color 3 `#FFDDA7`


### Icon colors
Matching other parts of the interface, these are the colors that icons in Spyder may use. Whenever possible, use single color icons especially in Icon color 1. 
<img width="851" alt="2-14icon" src="https://user-images.githubusercontent.com/50221806/95834741-2eb27b80-0cf2-11eb-80ce-e9c16dab2312.png">
Icon color 1 `#FAFAFA`
Icon color 2 `#3498DB`
Icon color 3 `#20C997`
Icon color 4 `#E74C3C`
Icon color 5 `#F39C12`
Icon color 6 `#37414F`

### Border colors
Border colors are used for details that divide the Spyder UI further. They overlap with background colors.
<img width="848" alt="2-14border" src="https://user-images.githubusercontent.com/50221806/95835547-36beeb00-0cf3-11eb-85b2-a2670e40a590.png">
Border color 1 `#455364`
Border color 2 `#455364`
Border color 3 `#54687A`
Border color 4 `#60798B`
Border color 5 `#788D9C`

### Group colors
This name could still be refined. These are a set of colors designed to provide variety and help sections of Spyder with  several items be easier to tell apart. Originally designed for the Variable Explorer's variables, this can also be used to represent different types areas of Code Analysis of Projects as needed. These colors are meant to be used very sparingly and only grouped with others of its set. They should not be used for text as this set is not optimized for high contrast.
<img width="850" alt="2-14group" src="https://user-images.githubusercontent.com/50221806/95835574-3e7e8f80-0cf3-11eb-89d8-323b661117ce.png">
Group color 1 `#E11C1C`
Group color 2 `#FF8A00`
Group color 3 `#88BA00`
Group color 4 `#2DB500`
Group color 5 `#3FC6F0`
Group color 6 `#107EEC`
Group color 7 `#5C47E0`
Group color 8 `#7F27C5`
Group color 9 `#C88AFA`
Group color 10 `#AF2294`
Group color 11 `#DB4D8E`
Group color 12 `#38D4A4`

**Comment by isabela-pf** [comment]
As previously mentioned, I'm also trying to set up a color system that makes
1. a sustainable/adaptable approach
2. accessibility a priority and with a lot of options
3. a cohesive set within a single mode and between light and dark modes

I’m testing a way to represent the system’s relation to itself helpfully. As I mentioned having a full color scale earlier, here it is as a value grid. 0 is always black `#000000` and 150 is always white `#ffffff`. Everything in between is a scale for a selected hue (gray, blue, green, red and orange). Numbers indicate value.

The group set is the exception, as it’s not a scale of a single hue. That’s why it isn’t shown in the grid.

<img width="1646" alt="color families 0-4" src="https://user-images.githubusercontent.com/50221806/95842553-86091980-0cfb-11eb-9fce-11f8f1b230a0.png">


Color names are separate from the scale numbers so that the colors can be switched out without changing the way a color is called in the code (so the definition only needs to be changed in one place in the future).

I didn’t create a full set for each color because it wasn’t needed and I thought it might become overwhelming with the number of choices (similar to how Spyder might feel now). Because I aligned the shorter scales with the same number system as the full grey scale, though, the sets can easily be extended if needed.

I’ve been trying to come up with a way to set the naming of the colors to help people evaluate the accessibility of a color combo (like what [IBM’s Carbon](https://www.carbondesignsystem.com/guidelines/color/overview/) does), but so far I have not found an effective way to implement it with the range of colors Spyder needs. I’m noting it because it’s something that I’d love to get more ideas on and return to.

**Comment by isabela-pf** [comment]
Another revision for the proposed color system! Here’s what’s changed in this round: 
- Shifted lighter blues (110 and up) to be less cyan (per meeting feedback)
- Added highlight colors set (per meeting feedback)
- Lowered number of background, text, and border colors by one. This is likely the range that will be used, I’ve just experienced limits around having only four options in the past. With the addition of the highlight colors this might work fine since highlighted areas and disabled buttons are usually the places where I see the need for more contrast than four colors allows.
- Added a light mode proposal (finally :tada:). Many of the colors are the same, some are the inverse of their values (based on the color scales shown previously), and the group colors match what was agreed upon in #7.

### Dark Mode
<img width="852" alt="3-20" src="https://user-images.githubusercontent.com/50221806/96526789-72960b00-1233-11eb-875e-ec6e8bd0717c.png">

### Light Mode
<img width="852" alt="3-21" src="https://user-images.githubusercontent.com/50221806/96526807-7cb80980-1233-11eb-851d-d224a15493d0.png">
As usual, here’s how that might look in Spyder:

### Dark mode
<img width="559" alt="3-20 Test-2" src="https://user-images.githubusercontent.com/50221806/96526869-a2dda980-1233-11eb-86b1-e2a4cedde7ab.png">
<img width="550" alt="3-20 Test" src="https://user-images.githubusercontent.com/50221806/96526874-a4a76d00-1233-11eb-89ca-64cf3d352f23.png">
<img width="499" alt="3-20 Test-1" src="https://user-images.githubusercontent.com/50221806/96526877-a6713080-1233-11eb-9e5f-aab4d3b15554.png">

### Light mode
<img width="559" alt="3-21 Test-3" src="https://user-images.githubusercontent.com/50221806/96526895-b1c45c00-1233-11eb-9d41-ecab5a66e38b.png">
<img width="550" alt="3-21 Test" src="https://user-images.githubusercontent.com/50221806/96526899-b426b600-1233-11eb-8e80-7e27ac24fc2a.png">
<img width="499" alt="3-21 Test-1" src="https://user-images.githubusercontent.com/50221806/96526902-b6891000-1233-11eb-9114-6029dfcbf0dc.png">

I think light mode still needs some work to make sure it looks as good as it can, and that will reflect on dark mode too. 

Most of the reversing of colors is working well enough in light mode, but the main problem I’m having is in the text colors. Specifically, I’m noticing that buttons would be set as having black text (like above) instead of the white text that I think is more legible and familiar (like below). 
<img width="499" alt="3-21 Test-2" src="https://user-images.githubusercontent.com/50221806/96526918-be48b480-1233-11eb-9219-728ab1ff3a52.png">
Since in dark mode buttons can use the same color as the rest of the main text, I have no section set up to separate the uses of text. So to keep the variable names the same across themes and switch definitions alone (what I think might be the easiest way to set up the system in Spyder), I would have to set up something besides just “text.” This can be done, but I’d appreciate feedback on
1.  if that system of variables makes sense/seems like a good choice on the code side, and
2.  if there is any desired system anyone else has in mind.

**Comment by juanis2112** [comment]
We need to add colors for matches in find and occurrences.

Cursor position word occurrences:
<img width="234" alt="Screenshot 2020-10-20 at 6 29 51 PM" src="https://user-images.githubusercontent.com/18587879/96655072-409faa00-1302-11eb-99c1-a2e060ade4e1.png">

Matches in find widget:
<img width="705" alt="Screenshot 2020-10-20 at 6 31 12 PM" src="https://user-images.githubusercontent.com/18587879/96655156-72187580-1302-11eb-8096-070185f4d9d4.png">

**Comment by isabela-pf** [comment]
Here's the latest updates based on in-meeting feedback! Changes are as follows:

- Added inverse text class. These account for the buttons needing to be reversed-out text (white on a color) in both dark and light mode and ensure a smooth flip between modes.
- Updated accent and feedback colors for higher saturation and better contrast. The feedback asked specifically for lighter blues, but this is as close as we can get while keeping sufficient contrast. Making them more true blue blues should make them feel a little lighter. I mildly change the feedback colors to match. 
- Added what I'm calling the find colors. They are the set of highlight colors for find and occurrences as requested in the above comment.
- Added back a fifth background color so the grey buttons (or other inverse areas of UI) can change modes accurately. They are intentionally the same color.

As usual, below is all that information color by color and mocked up.
### Dark Mode
<img width="852" alt="4-29 (color families 4-7 applied)" src="https://user-images.githubusercontent.com/50221806/97657640-a3dabc00-1a27-11eb-9e40-357cce3e7dd3.png">
<img width="559" alt="4-29 Test-2" src="https://user-images.githubusercontent.com/50221806/97657681-bd7c0380-1a27-11eb-9de5-74f4d7f76ad2.png">
<img width="550" alt="4-29 Test" src="https://user-images.githubusercontent.com/50221806/97657685-bfde5d80-1a27-11eb-8d36-6505955a2f58.png">
<img width="499" alt="4-29 Test-1" src="https://user-images.githubusercontent.com/50221806/97657687-c1a82100-1a27-11eb-8a8c-38db6f7d388c.png">

### Light Mode
<img width="852" alt="4-30 (Light Mode of 4-29)" src="https://user-images.githubusercontent.com/50221806/97657728-d2589700-1a27-11eb-96e9-485939569da2.png">
<img width="559" alt="4-30 Test-2" src="https://user-images.githubusercontent.com/50221806/97657735-d7b5e180-1a27-11eb-9eb2-c2c41e7a8b2e.png">
<img width="550" alt="4-30 Test" src="https://user-images.githubusercontent.com/50221806/97657741-da183b80-1a27-11eb-8444-3c2c7be8626e.png">
<img width="499" alt="4-30 Test-1" src="https://user-images.githubusercontent.com/50221806/97657744-dbe1ff00-1a27-11eb-8136-9dd874d90e5d.png">

**Comment by ccordoba12** [comment]
- [ ] Email Qdarkstyle maintainer (Carlos, CC Juanita and Isabella).
- [ ] Lists of colors that we'll need to change in Qdarkstyle and colors that we need only in Spyder (Isabella)
- [ ] List with places in Spyder that define colors we use (Juanita and Isabella)

**Comment by isabela-pf** [comment]
When reviewing these last options in meetings, we discussed how Spyder’s colors pulls from multiple sources with the most important distinction (in code) being whether sets of colors are originally from to QDarkStyle or not. 

First, below are the proposed colors categories that are closest to, derive from, and would need to replace current QDarkStyle.
- Background
- Text
- Inverse text
- Accent
- Border

<img width="850" alt="QDarkStylerep" src="https://user-images.githubusercontent.com/50221806/101256944-6c20fd00-36d4-11eb-8f58-2cfd7b4b0a46.png">

The following colors are currently not tied to QDarkStyle and don’t necessarily need to be in the future.

- Info/Feedback
- Icon
- Highlight
- Find
- Group

<img width="852" alt="nonQDarkStyle" src="https://user-images.githubusercontent.com/50221806/101257014-72af7480-36d4-11eb-934f-aec4940d6c81.png">

**Comment by dpizetta** [comment]
Hi, just to document as you are planning to make some changes in the QDarkStyle, the main palette we use is [here](https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/images/palette.svg). The icons and images were recently improved too (of course not professionally as it is being planned now). So, thank you so much for those improvements.

**Comment by juanis2112** [comment]
After the meeting:

1. Open an issue on the Qdarkstyle repo linking this issue
2. Collecting all colors in Spyder as constants in a file called "palette.py" 
3. PR adding the new colors to the main Qdarkstyle's file (with the new names) and adding the new file with the system scale file.
4. PR with markdown file with the color samples.

**Comment by isabela-pf** [comment]
I've updated the examples I showed in our last meeting and have them ready to be accessed as needed. There's still details to be worked out, but I gave my best guess of what it should look like based on current QDarkStyle.

- [palette.py](https://github.com/isabela-pf/QDarkStyleSheet/blob/13example/qdarkstyle/palette.py) is updated based on what I think it might look like.
- [colorsystem.py](https://github.com/isabela-pf/QDarkStyleSheet/blob/13example/qdarkstyle/colorsystem.py) is a new file that lists all the constants that make up the color system.
- [colorreference.md](https://github.com/isabela-pf/QDarkStyleSheet/blob/colordocs/docs/colorreference.md) is the initial form of color docs that allows for easy reference for what they system has to offer and what default light and dark mode are. There might need to be other information, but I don't know what else makes sense yet.

Let me know if you have any feedback or questions. Hope this helps.

**Comment by isabela-pf** [comment]
It was brought to my attention in a meeting today that I never posted an image of the fully filled out color scales here! For reference, this is what the color system looks like in one non-code place. These will also be recorded in docs as they are implemented.
<img width="1646" alt="color families 4-7 (full)" src="https://user-images.githubusercontent.com/50221806/104063752-848fa600-51b1-11eb-860d-c70f02f70f1a.png">

**Comment by isabela-pf** [comment]
Based on work in [spyder #13963](https://github.com/spyder-ide/spyder/pull/13963), there was a request to adjust light mode's info colors to make them look softer on the light background but still dark enough to meet contrast requirements for the light text they are often used with.

1 is the set of colors used for inverted text like in the issue, so that is what I will focus on for this post. If we decide to change these colors, I can shift the pattern for each of the constants accordingly.

### Current light mode info colors (option 1)
<img width="619" alt="Screen Shot 2021-02-11 at 9 54 20 PM" src="https://user-images.githubusercontent.com/50221806/107735107-cd0c1900-6cb3-11eb-891f-2ddfb4e65e5e.png">

In the full set this looks like
<img width="998" alt="Screen Shot 2021-02-11 at 9 52 40 PM" src="https://user-images.githubusercontent.com/50221806/107735321-4572da00-6cb4-11eb-8171-201ef74a887d.png">

- Success color 1: green 40 `#008760`
- Error color 1: red 40 `#D4140B`
- Warn color 1: orange 40 `#CE4B01`

All these options pass with `#FAFAFA` text as is often used for buttons or other feedback. Moving the colors even one step lighter (green 50 `#019D70`, red 50 `#DE321F`, and orange 50 `#E05E15`) does not have enough contrast.

### Light mode with dark text (option 2)
Personally, I prefer the light text on darker colors option, but since we can't get lighter with white text while keeping contrast I wanted to give another option. Here is the first color on the scales that is light enough to have contrast for `#19232D`text.

<img width="652" alt="Screen Shot 2021-02-11 at 10 07 04 PM" src="https://user-images.githubusercontent.com/50221806/107736114-1fe6d000-6cb6-11eb-84a3-ee2303d2f4f6.png">

In the full set this looks like
<img width="995" alt="Screen Shot 2021-02-11 at 10 07 41 PM" src="https://user-images.githubusercontent.com/50221806/107736140-2e34ec00-6cb6-11eb-8ed9-cc60ee2f96f1.png">

- Success color 1: green 80 `#44DEB0`
- Error color 1: red 80 `#F66657`
- Warn color 1: orange 80 `#FF993B`

### All my tests
In case you wanted to see the other options I tried, here's a quick overview of the combinations and whether they pass or fail standards for the text color they show for everything not already shown above.

<img width="657" alt="Screen Shot 2021-02-11 at 10 16 40 PM" src="https://user-images.githubusercontent.com/50221806/107736413-db0f6900-6cb6-11eb-9bf9-d99613d7e2fc.png">

**Comment by juanis2112** [comment]
Thanks @isabela-pf I don't really like the options with dark text so I would prefer option 1. What do you think @ccordoba12 and @steff456?

**Comment by juanis2112** [comment]
@isabela-pf and I met to discuss about the light theme and we have our first attempt. (Notice that since the code infraestructure is not yet implemented, there are things that are still dark that will not be). We will appreciate your feedback as soon as possible so we can continue iterating.
<details>

Main Window (with selection color of editor):

<img width="1440" alt="Screenshot 2021-03-18 at 6 59 40 PM" src="https://user-images.githubusercontent.com/18587879/111713584-eefe3b80-881d-11eb-9e2b-2e49b7e53248.png">

Menus with hover:
<img width="725" alt="Screenshot 2021-03-18 at 6 59 56 PM" src="https://user-images.githubusercontent.com/18587879/111713640-0c330a00-881e-11eb-91bf-56c70ef8aa5f.png">

Tabs (hover and pressed states):

<img width="247" alt="Screenshot 2021-03-18 at 7 00 08 PM" src="https://user-images.githubusercontent.com/18587879/111713686-1c4ae980-881e-11eb-91cb-839cb8bea695.png">

Files pane (hover and selected item) (Also notice color of hover for the small arrows)

<img width="718" alt="Screenshot 2021-03-18 at 7 00 23 PM" src="https://user-images.githubusercontent.com/18587879/111713722-2d93f600-881e-11eb-96a8-d386719c09f0.png">

Scrollbar hover:

<img width="724" alt="Screenshot 2021-03-18 at 7 00 49 PM" src="https://user-images.githubusercontent.com/18587879/111713787-46041080-881e-11eb-850b-f71edec127ee.png">

Tooltip:

<img width="669" alt="Screenshot 2021-03-18 at 7 01 03 PM" src="https://user-images.githubusercontent.com/18587879/111713868-69c75680-881e-11eb-82f0-60c3040ba69b.png">

Preferences dialog (hover for buttons)

(@isabela-pf looking at this, we might need to move the hover color a bit more)
<img width="1045" alt="Screenshot 2021-03-18 at 7 01 42 PM" src="https://user-images.githubusercontent.com/18587879/111713950-94b1aa80-881e-11eb-9c2e-b9348b0fa27a.png">

Hover color for "images" (Radio buttons)

<img width="1047" alt="Screenshot 2021-03-18 at 7 02 10 PM" src="https://user-images.githubusercontent.com/18587879/111714008-b3b03c80-881e-11eb-8269-8daa7140013a.png">

Hover color for "images" (X in tabs)

<img width="172" alt="Screenshot 2021-03-18 at 7 02 30 PM" src="https://user-images.githubusercontent.com/18587879/111714034-c0cd2b80-881e-11eb-8ba2-77c2e1c3b002.png">

Pane toolbars (hover and pressed states)

<img width="220" alt="Screenshot 2021-03-18 at 7 02 43 PM" src="https://user-images.githubusercontent.com/18587879/111714051-cdea1a80-881e-11eb-8f60-2a187702c89e.png">


</details>

**Comment by dpizetta** [comment]
Some points to me:

Maybe the color for the menu selection can be darker like the line in the tab selection.

![image](https://user-images.githubusercontent.com/5084939/111726848-76f93b00-8848-11eb-80a0-a639620cb459.png)

The dark tab (selected) calls me too much attention. Since it has a blue bar indicator we can keep the same color as the other ones. Also, this color reduces the contrast with the tab title. Using a lighter color in the selected tab also improves the blue bar contrast. Check the second image, in which you can't see the details (or if you have myopia like me). Another option is just a lighter tone like the status bar color. Same for scrollbars (chrome example).

![image](https://user-images.githubusercontent.com/5084939/111726974-b58ef580-8848-11eb-8286-f8a0e44dac67.png)
![image](https://user-images.githubusercontent.com/5084939/111727051-e7a05780-8848-11eb-91bc-2b64c511d8c7.png)
![image](https://user-images.githubusercontent.com/5084939/111728154-0d2e6080-884b-11eb-8af1-af780166e6e0.png)

The last one, maybe I'm wrong but I think these buttons have different colors/states (at least n1), it seems tricky - without Spyder to check right now.

![image](https://user-images.githubusercontent.com/5084939/111727628-ff2c1000-8849-11eb-8010-a5a8e9a6bfd6.png)

All the other points seem amazing.

**Comment by juanis2112** [comment]
Thanks for your feedback @dpizetta I will try to address all your comments.
> Maybe the color for the menu selection can be darker like the line in the tab selection.

This color has the same problem we have in dark mode which is that this menu selection color is the same one as it is in the editor so we have to find an equilibrium between dark enough for contrast in menus and light enough that it's not too strong on top of the editor's text. 
This is how the editor selection would look if I use the color you are suggesting. I think it is a bit strong. However we are still working on the shades of blue since @ccordoba12 and @steff456 said in our last meeting that they would like to see a more "purplish" blue for all 5 shades of blue that we have.
<img width="689" alt="Screenshot 2021-03-21 at 11 31 09 AM" src="https://user-images.githubusercontent.com/18587879/111912730-f2b9da00-8a38-11eb-9013-e1658f3ebb3c.png">

> The dark tab (selected) calls me too much attention. Since it has a blue bar indicator we can keep the same color as the other ones. Also, this color reduces the contrast with the tab title. Using a lighter color in the selected tab also improves the blue bar contrast. Check the second image, in which you can't see the details (or if you have myopia like me). Another option is just a lighter tone like the status bar color. Same for scrollbars (chrome example).

Because of how the system is defined, I think is not possible to make the selected tab and the other ones the same color without assigning two accent colors to the same color, or affecting the dark mode. Right @isabela-pf? Though we can try to see if we can bring these two colors closer to each other. @ccordoba12 suggested to use darker greys in general since he thinks the whole interface looks too light so maybe when making this change the selected tabs won't call that much attention. 

> The last one, maybe I'm wrong but I think these buttons have different colors/states (at least n1), it seems tricky - without Spyder to check right now.

The "Edit selected scheme" button is supposed to be a hover state. Though it looks very similar to the others so we need to work that out with @isabela-pf. The "Apply" button is deactivated so the text in it is lighter.

**Comment by juanis2112** [comment]
The following screenshots are to try darker greys in general in the interface. (In these ones, the shades of blue remain the same)
<details>
<img width="1440" alt="Screenshot 2021-03-21 at 11 58 36 AM" src="https://user-images.githubusercontent.com/18587879/111913570-c607c180-8a3c-11eb-9d25-4d89f4ca0784.png">

<img width="1440" alt="Screenshot 2021-03-21 at 11 58 56 AM" src="https://user-images.githubusercontent.com/18587879/111913582-d15aed00-8a3c-11eb-9264-e561896dc4c6.png">
<img width="1440" alt="Screenshot 2021-03-21 at 11 59 07 AM" src="https://user-images.githubusercontent.com/18587879/111913588-d881fb00-8a3c-11eb-90b2-7d06340520bd.png">
<img width="1440" alt="Screenshot 2021-03-21 at 11 59 15 AM" src="https://user-images.githubusercontent.com/18587879/111913593-dd46af00-8a3c-11eb-9495-821ccdd2f500.png">
<img width="213" alt="Screenshot 2021-03-21 at 11 59 41 AM" src="https://user-images.githubusercontent.com/18587879/111913605-ed5e8e80-8a3c-11eb-8291-0a9cd1c2200b.png">
Hover:
<img width="487" alt="Screenshot 2021-03-21 at 12 01 44 PM" src="https://user-images.githubusercontent.com/18587879/111913674-36aede00-8a3d-11eb-9929-921f517749a3.png">
Pressed:
<img width="473" alt="Screenshot 2021-03-21 at 12 00 49 PM" src="https://user-images.githubusercontent.com/18587879/111913684-3f9faf80-8a3d-11eb-8a0a-6c957c596668.png">
<img width="307" alt="Screenshot 2021-03-21 at 12 02 16 PM" src="https://user-images.githubusercontent.com/18587879/111913695-49291780-8a3d-11eb-9ee2-6701395630f1.png">


</details>

**Comment by juanis2112** [comment]
The following screenshots are to try darker greys in general in the interface and also darker blues to show you how they look. 
<details>
<img width="1440" alt="Screenshot 2021-03-21 at 12 04 12 PM" src="https://user-images.githubusercontent.com/18587879/111913814-8ee5e000-8a3d-11eb-80fd-2281f83ed816.png">
<img width="287" alt="Screenshot 2021-03-21 at 12 04 27 PM" src="https://user-images.githubusercontent.com/18587879/111913821-96a58480-8a3d-11eb-8c8c-188da997ac25.png">
<img width="722" alt="Screenshot 2021-03-21 at 12 04 35 PM" src="https://user-images.githubusercontent.com/18587879/111913824-9b6a3880-8a3d-11eb-909f-cf8227dbdf5d.png">
<img width="718" alt="Screenshot 2021-03-21 at 12 04 50 PM" src="https://user-images.githubusercontent.com/18587879/111913831-a45b0a00-8a3d-11eb-8dee-296f943dbcee.png">
<img width="726" alt="Screenshot 2021-03-21 at 12 05 01 PM" src="https://user-images.githubusercontent.com/18587879/111913845-aae98180-8a3d-11eb-8743-e814156ab828.png">
<img width="1040" alt="Screenshot 2021-03-21 at 12 05 17 PM" src="https://user-images.githubusercontent.com/18587879/111913856-b472e980-8a3d-11eb-94bd-e2070c0f368a.png">
</details>

**Comment by juanis2112** [comment]
@ccordoba12 and @steff456 please let me know if the interface looks dark enough with these new shades of grey. We will rework the tone of blue with @isabela-pf. She is already working on these colors in the color system.

**Comment by ccordoba12** [comment]
Thanks @juanis2112 for your work on this! I really like the new shades of grey!

What do @isabela-pf and you think about them? Are they ok for you too?

**Comment by isabela-pf** [comment]
Hello! I've been summoned again! Here's some replies. 
>  Because of how the system is defined, I think is not possible to make the selected tab and the other ones the same color without assigning two accent colors to the same color, or affecting the dark mode. Right @isabela-pf? Though we can try to see if we can bring these two colors closer to each other. 

It would definitely take some kind of workaround to make all the tabs the same color without touching dark mode. I don’t know that it is possible at all since that color is used in other places where I don’t think we would want them all to match. We can adjust colors though. This color has once again been a challenge because of its relationship to the various button states, so that’s how it became darker than some of the first passes.

> The "Edit selected scheme" button is supposed to be a hover state. Though it looks very similar to the others so we need to work that out with @isabela-pf. The "Apply" button is deactivated so the text in it is lighter.

Noted! Thanks for catching this.

> What do @isabela-pf and you think about them? Are they ok for you too?

I can make this work, but I’m not certain why we want the entire interface darker. Already some areas are starting to look lower contrast. The more we move toward a middle range of values, the harder I think it is going to be to find solutions for some of the problem areas we already have. For example, we already are having trouble with finding a selection color that works well on the light mode editor themes (such as the almost white default Spyder one here) compared to the middle grey menus. With the darker overall interface, the selection color still has to work for almost white to an even darker grey. I’m happy to do my best to make this work since I think it’s still possible to find a solution, I just want to warn that we may find ourselves compromising a lot along the way.

**Comment by ccordoba12** [comment]
> I can make this work, but I’m not certain why we want the entire interface darker. Already some areas are starting to look lower contrast

I think you're right and sorry for pushing in that direction. This weekend I made the light theme work on the QDarkstyle repo, so I had a chance of seeing it live on my end:

![imagen](https://user-images.githubusercontent.com/365293/112067779-a5239700-8b36-11eb-8c68-6e93421f06ff.png)

And I think the theme looks pretty good already!
