### ISSUE TITLE
Change the color for the tooltips

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/ux-improvements#2]

**Comment by isabela-pf** [comment]
Because the current tooltips are a low contrast black text on medium blue, I’m proposing to change the colors to higher contrast options and increase legibility.

I’ve mocked up three color options see how they look with the rest of the Spyder UI colors. All proposals pass minimum contrast recommendations by [WCAG 2.1](https://www.w3.org/TR/WCAG21/#contrast-minimum).

![Blue 3](https://user-images.githubusercontent.com/50221806/87321693-69352e00-c4e1-11ea-8f06-9d75f3f0aeba.png)
The blue version is closest to the current experience; to meet contrast standards I did have to use a blue that does not currently exist in Spyder.

![Dark 1](https://user-images.githubusercontent.com/50221806/87321733-78b47700-c4e1-11ea-9342-6003238ca956.png)
The dark version blends in the most, which has pros and cons. It fits well with the existing UI, but it also is the hardest one to spot which may not be ideal for a tooltip. I did find some applications using dark tooltips in a dark UI even though it did not seem to be the most common choice.

![Light 1](https://user-images.githubusercontent.com/50221806/87321778-823ddf00-c4e1-11ea-81f8-6415c0162588.png)
The light version stands out the most. Surprisingly, light tooltips in a dark UI seems to be relatively standard in other applications I explored. 

I think any of these options could work well, so feedback is welcome. I’ll be happy to post the exact specs for whichever direction we decide to pursue.

**Comment by isabela-pf** [comment]
When meeting with @juanis2112  and @ccordoba12, we decided to go with the blue option. I've listed the specs below:
- Blue background is `#3775A9` 
- White text is `#F5F5F5`
- Shadow is `0px 0px 8px rgba(0, 0, 0, 0.5)`

**Comment by isabela-pf** [comment]
Quickly updating this with some very simple mockups showing the tooltips with the WIP color system as it is now at #13. Many of the colors are the same and were based on this original work. I'll keep coming back to this as more significant changes are made.

![Blue 4](https://user-images.githubusercontent.com/50221806/96640111-8e52ed00-12d7-11eb-84f7-6ef37825813a.png)
![Blue 4 Light](https://user-images.githubusercontent.com/50221806/96640117-90b54700-12d7-11eb-9579-6030606fb36a.png)

**Comment by juanis2112** [comment]
We will like to see lighter shades of blue for both themes.

**Comment by juanis2112** [comment]
Closing with https://github.com/spyder-ide/spyder/pull/14665
