### ISSUE TITLE
Migrate icons to material design

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/ux-improvements#33]
Here is the list of icons that need a completely new design along with ideas for them. (I will be updating this list as we go through the icons in our list)

- [x]  General Preferences 
<img width="24" alt="general preferences 0-2" src="https://user-images.githubusercontent.com/50221806/111725228-f3c5ee00-8823-11eb-92d2-3e531b85a309.png">

- [x] Show sys path contents
-> All caps, No outline, 3 letters
<img width="24" alt="sys-2-14" src="https://user-images.githubusercontent.com/50221806/111725240-fa546580-8823-11eb-8913-c631003cab47.png">

- [x] Show environment variables
-> All caps, No outline, 3 letters
<img width="24" alt="env-2-16" src="https://user-images.githubusercontent.com/50221806/111725252-fde7ec80-8823-11eb-8a21-a014a6116c04.png">

- [x] Delete all (for plots)
-> First option (bigger gap between outlines)
<img width="24" alt="delete 0-2" src="https://user-images.githubusercontent.com/50221806/111710656-552b9400-8807-11eb-86fd-a2e97a078ccc.png">

- [x] Close all (files menu)
-> New one with more spacing
<img width="24" alt="close 1-5" src="https://user-images.githubusercontent.com/50221806/111710637-4d6bef80-8807-11eb-812b-f116101fda94.png">

- [x] Run configuration per file 
-> Smaller run button (Option 1)
<img width="24" alt="run settings 0-6" src="https://user-images.githubusercontent.com/50221806/111710981-07fbf200-8808-11eb-8596-06aee4970381.png">

- [x] Run file again
-> :)
<img width="24" alt="run again 0-8" src="https://user-images.githubusercontent.com/50221806/111710681-5d83cf00-8807-11eb-98d0-1349cb13c1dd.png">

- [x] Run selection
-> :)
<img width="24" alt="run selection 0-5" src="https://user-images.githubusercontent.com/50221806/111710691-61afec80-8807-11eb-8b06-298e09ef0905.png">

- [ ] Run cell

- [ ] Debug cell

- [ ] Run cell and advance

- [x] Last edit location
-> :)
<img width="24" alt="last-edit-location-0-4" src="https://user-images.githubusercontent.com/50221806/111725283-08a28180-8824-11eb-89b6-6cbc5b654394.png">

- [x] Maximize/ Unmaximize
-> Option 3 :)
<img width="24" alt="maximise-pane-0-20" src="https://user-images.githubusercontent.com/50221806/111725296-0d673580-8824-11eb-9bac-e6d195e5f3f9.png">

- [ ] New package
(mdi-folder-plus + "Py")

- [x] Compressed file 
-> First option with cut out :)
<img width="24" alt="compressed-file-0-5" src="https://user-images.githubusercontent.com/50221806/111725320-16580700-8824-11eb-9b2d-181eab29debd.png">

- [ ] Reset to factory default
- [ ] Horizontal split
- [ ] Dock
- [ ] PyLint
- [ ] Find next
- [ ] Find previous

**Comment by isabela-pf** [comment]
Since we have a lot of icons to review and not a lot of time to do it, I will be posting icons in batches as we point out which ones need customization. Our first round is Show sys.path contents and Show environment variables.

After some discussion about how abstract these commands are, we ended up agreeing to explore text-based icons. Based on existing Material icons with text, this is what I have for your consideration.

### Show sys.path content
I'm not sure if there's a preferred abbreviation for this, so I've provided both SPC and SYS icons.

Rectangle
<img width="24" alt="sys-0-12" src="https://user-images.githubusercontent.com/50221806/106965997-5b532e80-66f9-11eb-9c8c-d54cbbc9c4b3.png">
<img width="24" alt="sys-0-14" src="https://user-images.githubusercontent.com/50221806/106965999-5bebc500-66f9-11eb-8e11-3ebc2d67b2dd.png">

Text only
<img width="24" alt="sys-0-17" src="https://user-images.githubusercontent.com/50221806/106966014-60b07900-66f9-11eb-8fe8-6f085171e44e.png">
<img width="24" alt="sys-0-16" src="https://user-images.githubusercontent.com/50221806/106966021-6312d300-66f9-11eb-82b1-d8f2bbeb5960.png">

### Show environment variables
Rectangle
<img width="24" alt="env-0-10" src="https://user-images.githubusercontent.com/50221806/106965851-1fb86480-66f9-11eb-98ff-ed88d450f89d.png">

Text only
<img width="24" alt="env-0-11" src="https://user-images.githubusercontent.com/50221806/106965873-2d6dea00-66f9-11eb-9756-f31526621607.png">

### In the interface
(I use SYS as the sys.path content example)

Rectangle
<img width="310" alt="0-1sysenv mockup2" src="https://user-images.githubusercontent.com/50221806/106965411-6ce80680-66f8-11eb-9515-1055f2834dd3.png">
Text only
<img width="310" alt="0-1sysenv mockup3" src="https://user-images.githubusercontent.com/50221806/106965415-6eb1ca00-66f8-11eb-9bc9-e3f994a094aa.png">

**Comment by juanis2112** [comment]
I like the rectangle option for both and I think SPC should be better since I think SYS is used for other things.

**Comment by ccordoba12** [comment]
Thanks @isabela-pf for your work on this! I must say that I like this idea a lot! I think it'll help us to solve several issues with icons for which it's hard to come up with a design.

The main problem I see with the draft you posted above is that the font you selected is too thick, so it's really hard to tell the difference between `ENV` and `SYS` by reading them. So perhaps selecting a thinner font could solve that?

**Comment by isabela-pf** [comment]
@ccordoba12 I agree that it is harder to distinguish them in the rectangles. I can use a thinner font, but right now I am piecing together text from these existing Material Design icons and their [guidelines](https://material.io/design/iconography/system-icons.html#design-principles).

<img width="247" alt="Screen Shot 2021-02-11 at 7 33 29 PM" src="https://user-images.githubusercontent.com/50221806/107727857-36366100-6ca1-11eb-8bbd-ba67846d772a.png">
<img width="276" alt="Screen Shot 2021-02-11 at 7 30 40 PM" src="https://user-images.githubusercontent.com/50221806/107727862-36cef780-6ca1-11eb-8914-994c20bc4e0a.png">

I can experiment with other fonts and have a more Spyder-specific case of letter-based icons if you are interested. If not, I think the non-rectangle options are slightly more easy to tell apart, though I'd appreciate your thoughts on that as well.

(Also thanks @juanis2112 for letting me know spc is the better abbreviation)

**Comment by ccordoba12** [comment]
> I can experiment with other fonts and have a more Spyder-specific case of letter-based icons if you are interested.

Yes, I am. I think other fonts (designed for small sizes) could look better.

**Comment by isabela-pf** [comment]
Also, I have two more icons based on our meeting! Here are Close all and Delete all. Both are modifications of the existing close and delete icons to match the "all" or "multiple" style of other material icons.

### Close all
<img width="24" alt="close 0-2 (1)" src="https://user-images.githubusercontent.com/50221806/107728807-f4f38080-6ca3-11eb-82cf-469d4d8b45e3.png">

### Delete all
The first option is a more dramatic stack of the two trash cans.
<img width="24" alt="delete 0-2" src="https://user-images.githubusercontent.com/50221806/107728817-f9b83480-6ca3-11eb-9272-557d113ea26b.png">

The second option is more subtle. I think it might be harder to spot at small sizes, but considering it only exists next to the standard delete icon, it might be dramatic enough.
<img width="24" alt="delete 0-11" src="https://user-images.githubusercontent.com/50221806/107728826-ff157f00-6ca3-11eb-810a-67b25f018af0.png">

**Comment by ccordoba12** [comment]
> Close all

Mmmh, could you leave a bit bigger gap between the front and back Xs. Right now is hard to see that the icon actually displays two Xs. 

> Delete all

I like the first option a lot!

**Comment by isabela-pf** [comment]
The below icons following up on previous feedback. Thanks again for the info! Since these were smaller changes, I show the previous version side by side for easier comparison.

### Show sys.path content
Old
<img width="24" alt="sys-0-12" src="https://user-images.githubusercontent.com/50221806/106965997-5b532e80-66f9-11eb-9c8c-d54cbbc9c4b3.png">

New
<img width="24" alt="sys-1-2" src="https://user-images.githubusercontent.com/50221806/109578441-07dfc080-7aac-11eb-9f58-6041a5a64762.png">

### Show environment variables
Old
<img width="24" alt="env-0-10" src="https://user-images.githubusercontent.com/50221806/106965851-1fb86480-66f9-11eb-98ff-ed88d450f89d.png">

New
<img width="24" alt="env-1-2" src="https://user-images.githubusercontent.com/50221806/109578451-0b734780-7aac-11eb-9fa9-8841debeca7f.png">

The text has been changed from the custom type drawn from existing Material icons to [Rajdhani](https://fonts.google.com/specimen/Rajdhani?preview.text_type=custom#about), a condensed, geometric typeface that allows for more space within characters. Depending on the letters used, we may need to modify the font if we want to continue to use it. With both text-based icons mocked up in the menu, the new options look like this:
<img width="310" alt="env mockup1" src="https://user-images.githubusercontent.com/50221806/109578471-1201bf00-7aac-11eb-86c0-7d074859f617.png">

### Close all
Now with more spacing!
Old
<img width="24" alt="close 0-2 (1)" src="https://user-images.githubusercontent.com/50221806/107728807-f4f38080-6ca3-11eb-82cf-469d4d8b45e3.png">

New
<img width="24" alt="close 1-5" src="https://user-images.githubusercontent.com/50221806/109578481-16c67300-7aac-11eb-8fa9-7b7a49256026.png">

**Comment by isabela-pf** [comment]
I've got a few more simple updates for you all! These icons either recolor Material design icons or combine them.

### Run
<img width="24" alt="run" src="https://user-images.githubusercontent.com/50221806/109907756-d3106c80-7c57-11eb-956b-02d5473a8217.png">

### Run again
<img width="24" alt="run again 0-8" src="https://user-images.githubusercontent.com/50221806/109907768-d60b5d00-7c57-11eb-9734-4d3e723648cc.png">

### Run settings
I'm still experimenting with the size of the run portion while keeping the wrench easy to identify.

<img width="24" alt="run settings 0-6" src="https://user-images.githubusercontent.com/50221806/109907777-dad01100-7c57-11eb-9109-ff19d06a5a2e.png">

<img width="24" alt="run settings 0-3" src="https://user-images.githubusercontent.com/50221806/109907986-50d47800-7c58-11eb-9205-b78b8060cab9.png">


### Run selection
<img width="24" alt="run selection 0-4" src="https://user-images.githubusercontent.com/50221806/109907783-de639800-7c57-11eb-960d-f4886dce93d3.png">

I'm working on the cell-related icons in the main toolbar and am hoping to post them before the week is done. 🌻

**Comment by isabela-pf** [comment]
Cell-related icons are here! Because they are related, I was designing them together so they will work as a set. There are a two main options that I think will work. Just to be clear, I think we should choose one of the visual languages for all the icons not just a rectangle for one and tab cell for another. This makes sure that the idea of a cell is clear to users.

### Run current cell
Because I had heard in meetings that people were interested in having Spyder's cells represented as %% to reinforce the syntax, I did start by working with that idea. I don't think any of these icons are successful though since it creates a lot of small pieces in a single icon and many times is difficult to tell that it is a % sign at all. Some examples:

<img width="24" alt="run current cell 0-16" src="https://user-images.githubusercontent.com/50221806/110001059-d09a2b00-7cc8-11eb-8626-d7a3ffff1865.png">
<img width="24" alt="run current cell 0-1" src="https://user-images.githubusercontent.com/50221806/110001060-d132c180-7cc8-11eb-9973-88cb2c9bb36f.png">

As for directions I do think could work, my first option relies on the rectangle representation of the cell.

<img width="24" alt="run current cell 0-3" src="https://user-images.githubusercontent.com/50221806/110001213-fc1d1580-7cc8-11eb-82d2-cd4d8eb274ed.png">

The second option looks less like the literal cell. The idea is that you are running based on the active place you are in the editor, so the line serves as a kind of marker like the active tab markers in panes. Its definitely more ambiguous, but it works well across the multiple icons.

<img width="24" alt="run current cell 0-18" src="https://user-images.githubusercontent.com/50221806/110001222-fe7f6f80-7cc8-11eb-8a85-8a2ede357373.png">

### Run current cell and advance
Rectangle cell version

<img width="24" alt="run cell advance 0-4" src="https://user-images.githubusercontent.com/50221806/110002419-35a25080-7cca-11eb-95b3-5aaa537c6445.png">

Tab cell version

<img width="24" alt="run cell advance 0-5" src="https://user-images.githubusercontent.com/50221806/110002438-3cc95e80-7cca-11eb-809d-679308497cb9.png">

### Debug current cell
Rectangle cell version

<img width="24" alt="debug cell 0-2" src="https://user-images.githubusercontent.com/50221806/110002301-16a3be80-7cca-11eb-935d-a2232ebb6978.png">

Tab cell version

<img width="24" alt="debug cell 0-4" src="https://user-images.githubusercontent.com/50221806/110002326-1acfdc00-7cca-11eb-9e07-bffc1d64ab9d.png">

**Comment by ccordoba12** [comment]
@isabela-pf, things are looking pretty nice! Thanks for your work!

My comments so far:

> The text has been changed from the custom type drawn from existing Material icons to Rajdhani, a condensed, geometric typeface that allows for more space within characters

I think still think they are not readable. Perhaps we can find a different font? Or instead of using the filled version of those icons we could use the outlined one? I think that could help too.

> New
> <img width="24" alt="close 1-5" src="https://user-images.githubusercontent.com/50221806/109578481-16c67300-7aac-11eb-8fa9-7b7a49256026.png">

This one is ready for me.

> Run

I really like the shade of green you selected for this one, it's really nice!

> Run again

I also like it a lot!

> Run settings

I much prefer the second one.

> Run selection

This one is so cool! I know it didn't take much work to combine those two icons, but it looks really nice to me.

> Run current cell

Among the options you suggested, I really like the second one (i.e. the one with two percentages). But I have one suggestion: make the percentages bigger.

> Run current cell and advance

Double percentage and double play icon would work for me.

> Debug current cell

Again, I'd prefer the double percentage and play/pause button next to it.

**Comment by juanis2112** [comment]
Thanks! Let me know if I'm missing anything.

**Comment by isabela-pf** [comment]
Responding to @ccordoba12's request for cell based icons with the %% syntax incorporated, here are some ideas. 

Overall, this is a difficult request because of the number of pieces required to fit in one small icon (three for each percentage and at least one for the action being done to a cell for a minimum of 7 parts to the icon). This also means that elements overlap and sometimes cover enough of another portion to make it difficult to tell that it is a %. I think these are the options that work the best for the series of cell-based icons:

### Run cell
Vertical
<img width="24" alt="run current cell 1-28" src="https://user-images.githubusercontent.com/50221806/110694375-5a506980-819d-11eb-890a-222e06811fca.png">

Horizontal
<img width="24" alt="run current cell 3-34" src="https://user-images.githubusercontent.com/50221806/110694388-5d4b5a00-819d-11eb-9f8f-86c5ed2f7fa8.png">

### Debug cell
Vertical
<img width="24" alt="debug cell 1-7" src="https://user-images.githubusercontent.com/50221806/110694264-3c830480-819d-11eb-9c37-5542c5286802.png">

Horizontal
<img width="24" alt="debug cell 1-13" src="https://user-images.githubusercontent.com/50221806/110694273-3ee55e80-819d-11eb-998e-e91a8b782e0b.png">

### Run cell and advance
Vertical
<img width="24" alt="run cell advance 1-8" src="https://user-images.githubusercontent.com/50221806/110694360-558bb580-819d-11eb-9536-5fb72e4e6420.png">

Horizontal
<img width="24" alt="debug cell 1-14" src="https://user-images.githubusercontent.com/50221806/110694342-5290c500-819d-11eb-9b43-ed4ccd4de084.png">

**Comment by isabela-pf** [comment]
I also have some updates on text icons. Right now I am still using [Rajdhani](https://fonts.google.com/specimen/Rajdhani?preview.text_type=custom#about) because I have not found a font that I think is more legible at this size. 

### Outlined Box

Since there was a request for seeing the options outlined (since reversed cut out looking things like that can be harder to read), here it is.

<img width="24" alt="env-2-11" src="https://user-images.githubusercontent.com/50221806/110701197-b7501d80-81a5-11eb-9ffd-67d0f398632b.png">
<img width="24" alt="sys-2-13" src="https://user-images.githubusercontent.com/50221806/110701199-b7e8b400-81a5-11eb-8a4f-759d73242d90.png">
<img width="310" alt="2-1 sysenv mockup 5" src="https://user-images.githubusercontent.com/50221806/110701206-b9b27780-81a5-11eb-9297-7f9e08091b22.png">


I don't think it solves the problem because it is still forcing the text to be quite small. Since Material Design's icon specifications ask for 2pxs of distance between elements in a 24x24px icon, that means the letters are only about 14px wide when you have to account for the extra outlines. And since we are not displaying 24x24 icons at their full size, it gets even smaller in the menu. Because of this, I wanted to give some options that are just the text since I think these will end up being the most legible.

### All caps

<img width="24" alt="env-2-16" src="https://user-images.githubusercontent.com/50221806/110701389-f7af9b80-81a5-11eb-984a-e56b9ce4d93d.png">
<img width="24" alt="sys-2-14" src="https://user-images.githubusercontent.com/50221806/110701390-f8483200-81a5-11eb-98f2-32fcf1c7af31.png">
<img width="310" alt="2-1 sysenv mockup 1" src="https://user-images.githubusercontent.com/50221806/110701396-f9795f00-81a5-11eb-94ae-9271ce0adc90.png">

### All lowercase
Capital letters can also be harder to read because they all have the same height. It creates the visual effect of a straight line at small sizes, while using other cases can break that and be easier to identify. This isn't the case with the `env` here, but you can tell with the bottom of the p in `spc`.

<img width="24" alt="env-2-17" src="https://user-images.githubusercontent.com/50221806/110701613-3d6c6400-81a6-11eb-952a-1a1fde00cd47.png">
<img width="24" alt="sys-2-16" src="https://user-images.githubusercontent.com/50221806/110701615-3e04fa80-81a6-11eb-9708-e87576049a34.png">

<img width="310" alt="2-1 sysenv mockup 2" src="https://user-images.githubusercontent.com/50221806/110701636-49582600-81a6-11eb-883a-ad3ddc44e31c.png">

### Sentence/Camel case
Sentence/camel case—where both upper and lowercase characters are used—tends to be recommended as the easiest to read because it is most likely to create a distinctive shape (if you have questions about this, you can visit [figure 1.7 on this article](https://alistapart.com/article/how-we-read/)). Even though it may not be the most logical choice with our abbreviations, I wanted to try it since we are having such a legibility issue.

<img width="24" alt="env-2-18" src="https://user-images.githubusercontent.com/50221806/110701975-bd92c980-81a6-11eb-941b-f39174c264c8.png">
<img width="24" alt="sys-2-18" src="https://user-images.githubusercontent.com/50221806/110701977-be2b6000-81a6-11eb-8667-1dc08d83ea28.png">
<img width="310" alt="2-1 sysenv mockup 3" src="https://user-images.githubusercontent.com/50221806/110701983-c08dba00-81a6-11eb-8df3-495e4c9eb3ce.png">

### Further abbreviation
While we've had good reason to abbreviate these phrases with three letters, we can cut it shorter and allow the characters to be a little larger. For this example I've kept environments abbreviated as `env` both for comparing size with different character lengths and because `env` is the common abbreviation.

<img width="24" alt="sys-2-31" src="https://user-images.githubusercontent.com/50221806/110702182-0a76a000-81a7-11eb-93c2-a481f20cf138.png">
<img width="310" alt="2-1 sysenv mockup 4" src="https://user-images.githubusercontent.com/50221806/110702185-0d719080-81a7-11eb-88f1-625f21ee8389.png">

**Comment by isabela-pf** [comment]
Since I'm working through icons we haven't decided on yet, I also wanted to throw in one with simpler modifications to keep moving down the list. Here's `General Preferences` based on the above sketch.

<img width="24" alt="general preferences 0-2" src="https://user-images.githubusercontent.com/50221806/110702388-4dd10e80-81a7-11eb-8bf6-08c69b255874.png">

**Comment by isabela-pf** [comment]
Finishing off first versions for this list of icons, so here are a handful more of simple combined icons.

### Last edit location
<img width="24" alt="last-edit-location-0-4" src="https://user-images.githubusercontent.com/50221806/110868757-049fbe00-827e-11eb-8f6f-12f53ad30644.png">

### New package
<img width="24" alt="new-package-0-1" src="https://user-images.githubusercontent.com/50221806/110868770-079aae80-827e-11eb-8c99-8d456d7f287e.png">

### Compressed file
Depending whether or not we want to keep the cut out of the file corner, the zipper fits in different areas. I think either could work.

With cut out.
<img width="24" alt="compressed-file-0-5" src="https://user-images.githubusercontent.com/50221806/110868720-f0f45780-827d-11eb-9d83-2d315d8fcd1d.png">

Without cut out.
<img width="24" alt="compressed-file-0-7" src="https://user-images.githubusercontent.com/50221806/110868725-f18cee00-827d-11eb-9107-c398301baeb0.png">

**Comment by isabela-pf** [comment]
The last one on the current list (though I'm sure there are more that need to be done) is the maximize current pane icon! Right now there are two icons to maximize and minimize, but I think we can just have one button with a pressed state like we do with other icon buttons (such as the filter in the files pane). Let me know what you think!

### Maximize current pane

Option 1. The closest to the current icons.
<img width="24" alt="maximise-pane-0-11" src="https://user-images.githubusercontent.com/50221806/111231172-0d5a0200-85a6-11eb-88ae-121511b98601.png">

Option 2. 
<img width="24" alt="maximise-pane-0-19" src="https://user-images.githubusercontent.com/50221806/111231195-15b23d00-85a6-11eb-8e03-74bc5f3c5905.png">

Option 3.
<img width="24" alt="maximise-pane-0-20" src="https://user-images.githubusercontent.com/50221806/111231209-19de5a80-85a6-11eb-88f8-86a575ec3407.png">

**Comment by juanis2112** [comment]
We are changing icon color to Green.B60

**Comment by isabela-pf** [comment]
Following up on this week's feedback, here are a few more iterations! Thanks in advance for the feedback.

### New package
Because the icon on the folder must be so small, the Python logo became to hard to distinguish. Here it is abbreviated `Py`instead.
<img width="24" alt="new-package-0-2" src="https://user-images.githubusercontent.com/50221806/111732312-6b9b1500-8832-11eb-99cb-f656b58c286c.png">

### Reset Settings
This follows the other settings/preferences icon pattern and the pattern of sizes and placement for overlapping icons (such as `run again` and `last edit location`).
<img width="24" alt="reset settings 0-2" src="https://user-images.githubusercontent.com/50221806/111732319-6e960580-8832-11eb-9772-5cf021a3fc0e.png">

### Cell-based icons
We also reviewed `run cell`, `debug cell`, and `run cell and advance` as a group since they should use the same visual language. Even though these weren't everyone's favorite options individually, I polished this set of icons since some of us agreed that these work best for all three icons needed.
<img width="24" alt="run current cell 2-35" src="https://user-images.githubusercontent.com/50221806/111732588-0b58a300-8833-11eb-9b55-e9a540c5b4cf.png">
<img width="24" alt="debug cell 2-14" src="https://user-images.githubusercontent.com/50221806/111732592-0dbafd00-8833-11eb-984a-76e12ab5ad80.png">
<img width="24" alt="run cell advance 2-15" src="https://user-images.githubusercontent.com/50221806/111732594-0f84c080-8833-11eb-9855-43a084a9fa4b.png">

**Comment by ccordoba12** [comment]
I like all these icons @isabela-pf! Great work, as usual!

**Comment by isabela-pf** [comment]
I was double checking the full icon manager list to make sure I was ready to make the PR to Spyder as soon as it is ready when I found a few more icons that I missed. I added them to the first comment above and have them for you below. Let me know if anything seems amiss!

## Horizontal split
This is based off a Material icon that existed for a vertical split only. I kept the same shape and flipped the division.
<img width="24" alt="horizontal split 0-1" src="https://user-images.githubusercontent.com/50221806/111834214-81e7b600-88b0-11eb-8385-2049b76d96cd.png">

## Vertical split
I know I said that the vertical split icon already existed, but it is off center by one pixel in the original SVG. It became very noticeable in the horizontal split option since the sections were not able to be the same size. Because of this, I remade the vertical split option to match the horizontal split icon.
<img width="24" alt="vertical split 0-1" src="https://user-images.githubusercontent.com/50221806/111834519-f4589600-88b0-11eb-9bb6-658ccdad8d84.png">

### Dock
This icon already existed in Material design as `open-in-app`. I flipped the arrow down for our purposes.
<img width="24" alt="dock 0-1" src="https://user-images.githubusercontent.com/50221806/111834737-40a3d600-88b1-11eb-8494-628b4e301fa3.png">

### Pylint
This is currently a composed icon. Option 1 is in the same direction as the current composed icon but is resized to match the pattern of the other previously composed icons.
<img width="24" alt="pylint 0-1" src="https://user-images.githubusercontent.com/50221806/111835036-ab551180-88b1-11eb-9db0-5de781030f19.png">

### Find next and find previous
These ended up being the trickiest icons to remake because both of the original icons are a little wide and can obscure each other very easily. I've narrowed it down to two directions I think will work.

Option 1 is closest to the existing icons.
Find next
<img width="24" alt="find next 0-3" src="https://user-images.githubusercontent.com/50221806/111835670-785f4d80-88b2-11eb-8ade-51a34ac8a7d1.png">

Find  previous
<img width="24" alt="find previous 0-7" src="https://user-images.githubusercontent.com/50221806/111835706-8319e280-88b2-11eb-854e-c681844e2f71.png">

Option 2 takes advantage of the open space in the magnifying glass in order to allow both icons to be a little larger.
Find next
<img width="24" alt="find next 0-11" src="https://user-images.githubusercontent.com/50221806/111836137-118e6400-88b3-11eb-8704-c7c4229145c5.png">

Find previous
<img width="24" alt="find previous 0-5" src="https://user-images.githubusercontent.com/50221806/111836151-181cdb80-88b3-11eb-912e-afca6fe8cd38.png">

**Comment by isabela-pf** [comment]
Option 2 find next and previous!
