### ISSUE TITLE
Change design of pane tabs for them to look different to the tabs of the console and editor

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/ux-improvements#4]

**Comment by ccordoba12** [comment]
I think we could use rounded, colored tabs like the ones used by this app:

https://snapcraft.io/blog/canonical-enables-linux-desktop-app-support-with-flutter

**Comment by isabela-pf** [comment]
For clarification why I think this needs to be updated, I’ve circled the areas that are both called and designed to look like tabs. Since they control different things depending if they are on the top or bottom of a pane, it can be confusing that they share this name and visual language. 
![Frame 1](https://user-images.githubusercontent.com/50221806/88095649-4ee6fa00-cb4a-11ea-8167-7acfeebd4685.png)

Here are some proposals for ways to visually distinguish the lower tabs (the ones that control what panes are visible in a section) from their counterparts.

The first two mockups change the tabs to detached buttons. They differ in highlighted button color and a fill versus outlined state when not selected.

<img width="560" alt="2" src="https://user-images.githubusercontent.com/50221806/88095680-5908f880-cb4a-11ea-912e-c7f1171fd48a.png">
<img width="560" alt="4" src="https://user-images.githubusercontent.com/50221806/88095686-5ad2bc00-cb4a-11ea-8d74-3aa010ce8dac.png">

The following two mockups use text-only buttons with different selected and deselected styling.

<img width="560" alt="14" src="https://user-images.githubusercontent.com/50221806/88095741-6f16b900-cb4a-11ea-8543-0758df728495.png">
<img width="560" alt="15" src="https://user-images.githubusercontent.com/50221806/88095747-71791300-cb4a-11ea-88bb-5c504208d36f.png">

I think any of these approaches could work, it mostly depends if text-only buttons seem sufficient in a UI that doesn’t use them yet.

**Comment by isabela-pf** [comment]
I’ve also added more space between pane options, which means that not all panes that belong in that area can been seen at once. This necessitated adding a button to scroll through pane options in the upper right area. I’m not sure if this is the best approach, so feedback is welcome (as always).

**Comment by isabela-pf** [comment]
Feedback from the last round showed interest in the text-only buttons with blue highlights, but also agreed with the concerns I brought up about text-only buttons not yet existing in Spyder and maybe being confused for non-clickable text. 

These mockups try a toggle-inspired UI approach that limits the number of elements (like lines) that can clutter the small area, but still gives more indication that they are buttons than text alone.

There are three design elements (shown across mockups) I’d like to review in this iteration:
1. Toggle-inspired buttons
2. Background colors for this region of buttons (this is shown as the toggle area, but even if we decide against toggle-inspired styling this area could have a different color to distinguish it)
3. Divider lines between buttons

<img width="560" alt="23" src="https://user-images.githubusercontent.com/50221806/88419185-8f888280-cd99-11ea-9602-c6cb44d4f5b9.png">

(The above mockup is the iteration I think integrates best with current Spyder UI).


<img width="560" alt="24" src="https://user-images.githubusercontent.com/50221806/88419190-91524600-cd99-11ea-9b6c-6946198d869c.png">
<img width="560" alt="28" src="https://user-images.githubusercontent.com/50221806/88419193-931c0980-cd99-11ea-98b7-3e558ee8a919.png">

I’ve been testing out three possible background colors for this: `#071620` (which is not already in Spyder), `#32414B`, and `#505F69`. My favorite has been `#32414B`, however I’m not sure it has enough contrast from the blue highlight (`#1464A0`) which is why I tried others.

Divider lines can be found in these mockups:
<img width="560" alt="25" src="https://user-images.githubusercontent.com/50221806/88419025-4f290480-cd99-11ea-8044-17cee91bc230.png">
<img width="560" alt="26" src="https://user-images.githubusercontent.com/50221806/88419030-505a3180-cd99-11ea-95bd-c09160a83cca.png">
<img width="560" alt="27" src="https://user-images.githubusercontent.com/50221806/88419032-518b5e80-cd99-11ea-9ed5-769bf2c1d75e.png">

I don't think the divider lines add enough clarity to be worth the extra visual clutter, but I am interested in hearing if people think otherwise.

**Comment by juanis2112** [comment]
Summary form meeting:

1. Waiting on a color palette to decide colors
2. We like the line divider
3. We would like the bar to be symmetric so it would end after the arrow and the last portion of it should be the background color.

**Comment by isabela-pf** [comment]
Here's my next round of mockups based on feedback from the last meeting I had with some Spyder team members.

First, here's a version of the last round with a smaller and symmetrical pane display.
<img width="557" alt="29" src="https://user-images.githubusercontent.com/50221806/91783692-d302b780-ebb5-11ea-8a15-cf60a7ced3f3.png">

Working on this also made me realize I should make it more clear what panes could look like with a different number of them activated. Here it is with one pane:
<img width="560" alt="30" src="https://user-images.githubusercontent.com/50221806/91783764-fded0b80-ebb5-11ea-9dbd-b589d0841387.png">

And two panes: 
<img width="560" alt="31" src="https://user-images.githubusercontent.com/50221806/91783771-05141980-ebb6-11ea-8931-304d72fc9d7b.png">

Here's what it could look like when so many panes are active that users could have arrows on both sides:
<img width="560" alt="32 2" src="https://user-images.githubusercontent.com/50221806/91784117-ee21f700-ebb6-11ea-888e-1a74efa1c84a.png">

**Comment by isabela-pf** [comment]
### What happens if you can't see the open pane?
Another thing I started to explore is what happens when the currently open pane is outside the visible range because there are so many panes open. I haven't decided what the right direction might be, so here are a few ideas.

First, it could just always be on one edge of the bar and slightly covered. I don't like that the name isn't fully visible, so users would have to scroll to see what they have open if they don't recognize the pane.
<img width="560" alt="32" src="https://user-images.githubusercontent.com/50221806/91784031-abf8b580-ebb6-11ea-8485-04ab99c6ef7e.png">

Similarly, I don't like not having the open pane name visible here. Still, turning the arrow button blue to indicate hidden open content is another option, though not my favorite.
<img width="560" alt="33" src="https://user-images.githubusercontent.com/50221806/91784219-36411980-ebb7-11ea-8698-ffe80e840818.png">

One more idea is to always have the open pane be in the center of the panes listing. So whenever an a pane gets opened, it gets moved to the center automatically. This lets the pane name always be visible, which is a plus. The problem is I don't know if users would dislike panes names moving around at the bottom. I could see myself wanting them set up in a certain order to manage workflow or so I always know where to find it, and this approach would disrupt it.
<img width="560" alt="34" src="https://user-images.githubusercontent.com/50221806/91784360-920ba280-ebb7-11ea-990a-6d13019dbfc2.png">

Always open to more ideas, especially since I don't have this interaction worked out yet.

**Comment by juanis2112** [comment]
We like number 2 and we will wait on color palette for deciding on colors for this.

**Comment by isabela-pf** [comment]
Even though it isn't final yet, I wanted to provide some updated mockups with the colors I've been trying in #13. Still working out details, particularly in the dark and light mode relationship to each other. Here's what it is looking like now.

<img width="560" alt="38 (29 dark mode)" src="https://user-images.githubusercontent.com/50221806/96639932-446a0700-12d7-11eb-9602-e52b1be167c3.png">
<img width="560" alt="39 (29 light mode)" src="https://user-images.githubusercontent.com/50221806/96639937-46cc6100-12d7-11eb-81ba-89336294f5a4.png">

**Comment by juanis2112** [comment]
Same as #2 we will like to see a brighter shade of blue for the light mode

If the pipe line is not possible, we can implement tabs for panes as they are in light mode in MacOS
<img width="720" alt="Screenshot 2020-10-20 at 7 22 32 PM" src="https://user-images.githubusercontent.com/18587879/96658230-9c216600-1309-11eb-9f82-8f7e7ab509a2.png">
