### ISSUE TITLE
Improve design of the "About Spyder" logo

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/ux-improvements#40]
Current design:

<img width="461" alt="Screenshot 2021-04-06 at 3 07 25 PM" src="https://user-images.githubusercontent.com/18587879/113772067-cd3ff800-96e9-11eb-8b31-55fdf3c0eef5.png">

Idea: Firefox dialog

**Comment by isabela-pf** [comment]
Based on the feedback, there's the most interest in dividing the information up by tabs (like Spyder's panes) in order to keep it all without being overwhelming. Here is a first pass at a potential layout with more correct content. 

The Legal tab text will need to be updated based on the switched icons in Spyder 5.

<img width="559" alt="1-12" src="https://user-images.githubusercontent.com/50221806/120025444-895cc700-bfa5-11eb-9a27-130570155ad9.png">
<img width="559" alt="1-16" src="https://user-images.githubusercontent.com/50221806/120025448-8a8df400-bfa5-11eb-9373-de8676ecb705.png">
<img width="559" alt="1-17" src="https://user-images.githubusercontent.com/50221806/120025795-1142d100-bfa6-11eb-8a98-5d0b2b8fb799.png">

There was other feedback about making the logo larger or using the full word logo. While both of these are possible, it will require making the dialogue substantially bigger since the text can't be cut at all. I don't think this is ideal, but we can try it out again with whatever logo we end up with if desired.
Next to the tabs:
<img width="755" alt="1-15" src="https://user-images.githubusercontent.com/50221806/120026627-3257f180-bfa7-11eb-853a-bb5657e9c770.png">

Over the tabs (this does better with an actual logo instead of the box placeholder, by the way):
<img width="559" alt="1-18" src="https://user-images.githubusercontent.com/50221806/120026898-967ab580-bfa7-11eb-8016-839fd70d1a70.png">

**Comment by juanis2112** [comment]
We like option 1.

**Comment by juanis2112** [comment]
Pending:
1. Copy to clipboard button text. 
2. Right alignment of buttons (with respect to the tabs box)
3. Remove the version and commit from the overview tab. 
4. Add information about social media (overview tab) 
5. "Created by..:" should be in the community tab.
