### ISSUE TITLE
New design for splash screen.

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/ux-improvements#49]
Update splash screen to use the new logo and not use the photo that is currently used because it doesn't match the style of the logo.

**Comment by juanis2112** [comment]
Ideas:
1. Use a blurred screenshot of Spyder
2. Use red 
3. Use a "cute image"
For now we will go with ideas 1 and 2

**Comment by isabela-pf** [comment]
Hi there! Here are some simple ideas for Spyder splash screen that should fit better with Spyder’s UI. Because voting for logos is still open upon posting this, I’m using a messy rectangle stand in for now.

First are the simple, color only backgrounds (2 in the previous comment).

### Option 1-1
<img width="505" alt="0-12" src="https://user-images.githubusercontent.com/50221806/120240410-5587d880-c215-11eb-88e9-7f7f2886583a.png">

### Option 2-1
I liked this design with some different color combinations, so I’ve included them as the following three options.
<img width="505" alt="0-11" src="https://user-images.githubusercontent.com/50221806/120240417-5caee680-c215-11eb-9069-7fbd05da0230.png">

### Option 2-2
<img width="505" alt="0-4" src="https://user-images.githubusercontent.com/50221806/120240427-62a4c780-c215-11eb-8037-6c497fb475d2.png">

### Option 2-3
<img width="505" alt="0-6" src="https://user-images.githubusercontent.com/50221806/120240432-67697b80-c215-11eb-901c-4e3e0cf254da.png">

Second is using a photo for some additional texture. I’m just using a stock image as a placeholder right now since I remember hearing that there might be a certain Spyder photo you wanted to use. (1 in the previous comment)

### Option 3-1
<img width="505" alt="0-16" src="https://user-images.githubusercontent.com/50221806/120240444-6cc6c600-c215-11eb-8cf3-09128c27bad4.png">

**Comment by juanis2112** [comment]
We like option 1-1

Things to try:

1. We would like rounded corners for the rectangular shape
2. Splitting the screen into two colors: white + red. (Try both Texture and NO texture for the red part)
2. Splitting the screen between filled color RED (with the logo) and image (maybe Spyder screenshot)
3. Trying different shapes for the splash screen (not a rectangle)

**Comment by isabela-pf** [comment]
These aren't all the options requested above, but here are a few of the ideas I made while we were meeting. 

### Option 4-1
This splits the screen between two colors on an angle. I like the lighter background for the logo since it makes is feasible to use the full-color logo (still showing placeholders for now, though!).
<img width="505" alt="1-24" src="https://user-images.githubusercontent.com/50221806/120410974-df649e00-c308-11eb-9df9-621d244e1404.png">

### Option 4-2
This is 4-2 with an abstract texture for the red fill. This is one way to add a little more depth to a simple design but not be too heavy-handed by putting code everywhere.
<img width="505" alt="1-29" src="https://user-images.githubusercontent.com/50221806/120410985-e2f82500-c308-11eb-9e80-1bf8b4354a8c.png">

### Option 4-3
This is the requested split screen between red and a Spyder screenshot. As I mentioned in person, I think the red and blue of the screenshot have a similar amount of darkness that makes them blend together. It's not my favorite, but I will try some other options for this idea as I fill out some options for the next round.
<img width="505" alt="1-33" src="https://user-images.githubusercontent.com/50221806/120410991-e68bac00-c308-11eb-8208-b0aca288facc.png">

**Comment by isabela-pf** [comment]
Here's a few more options I've cooked up!

### Option 4-4
This is both an alternate shape (suggestion 4 above) and a different texture that could be applied to other shapes as well.
<img width="256" alt="2-43" src="https://user-images.githubusercontent.com/50221806/120865657-4e2d3b80-c543-11eb-8a4d-03e18dd0ce53.png">

### Option 5-1
There was also interest in include an image in a different way. Here's one idea (using images edited and combined from the [Spyder readme](https://github.com/spyder-ide/spyder/) and [unsplash](https://unsplash.com/photos/pypeCEaJeZY)). Depending on what we end up with, I can either try and shoot a similar image or we can use and credit the original.
<img width="505" alt="2-47" src="https://user-images.githubusercontent.com/50221806/120865685-5dac8480-c543-11eb-8acc-203ae80c65a3.png">

### Option 5-2
In terms of adding an image, this is my personal favorite. It is also a slightly different shape since the top of the image is cut out.
<img width="505" alt="2-45" src="https://user-images.githubusercontent.com/50221806/120866023-00fd9980-c544-11eb-908d-b29616239fbb.png">

**Comment by isabela-pf** [comment]
5-2 was the popular choice at the last meeting, but the team asked to see some variations on it. Using the same photo (and the updated logo), here are a few similar choices.

### Option 5-3
This is 5-2 with the updated logo and slightly heavier font for version number!
<img width="505" alt="3-48" src="https://user-images.githubusercontent.com/50221806/121608201-520b0300-ca06-11eb-9134-dc9626b953d1.png">

### Option 5-4
There was a request to see how this would look without the side of the face in the shot. With this image in particular, I think it looks empty and it would be tricky to edit in other items to fill the space with the perspective.
<img width="505" alt="3-49" src="https://user-images.githubusercontent.com/50221806/121608208-5505f380-ca06-11eb-82ca-f46600362ccf.png">

### Option 5-5
There was also a request to see this design in a more horizontal shape. I went back to my initial ratio of 2:1 while keeping the same photo (and extending it). Once again, this photo looks more empty in this case.
<img width="830" alt="3-51" src="https://user-images.githubusercontent.com/50221806/121608360-a2826080-ca06-11eb-9371-bcc189298dae.png">

**Comment by isabela-pf** [comment]
I'm back again! At our last discussion there was interest in seeing basically 5-3 with different photos. I have a few options with varying amounts of human, screen, and different background elements since those were some of the points of feedback. If we do end up using any photo, I'd want to credit the photographer in the about like we do with the icon sets we pull from.

(All of these could probably use a touch of clean up if they are the ones we want to go with.)

### Option 5-6
[Source](https://unsplash.com/photos/C3V88BOoRoM)
<img width="505" alt="4-64" src="https://user-images.githubusercontent.com/50221806/122452645-541d1680-cf5e-11eb-8929-799f96b94e7c.png">

### Option 5-7
[Source](https://unsplash.com/photos/a7A9O5htrKs)
<img width="505" alt="4-65" src="https://user-images.githubusercontent.com/50221806/122452659-567f7080-cf5e-11eb-9050-422e5af8e371.png">

### Option 5-8
[Source](https://unsplash.com/photos/k_T9Zj3SE8k)
This option is unusual in that it has far less screen/Spyder visible, but with all the comments about different backgrounds I wanted to include this as a very background focused alternative.
<img width="505" alt="4-66" src="https://user-images.githubusercontent.com/50221806/122452668-597a6100-cf5e-11eb-902d-759f6c3692ee.png">

### Option 5-9
[Source](https://unsplash.com/photos/2JDDn7iSGH8)
<img width="505" alt="4-67" src="https://user-images.githubusercontent.com/50221806/122452677-5c755180-cf5e-11eb-81a0-7c8b6dbd2ea5.png">

**Comment by isabela-pf** [comment]
I've gotten some more feedback to share the above option 5's without the diagonal cutouts to return to the rectangle. Here they are!

### Option 5-10
5-3's full image.
<img width="505" alt="5-72" src="https://user-images.githubusercontent.com/50221806/122497461-3a9dbe00-cfa2-11eb-8052-ebea68071a70.png">

### Option 5-11
5-6's full image.
<img width="505" alt="5-68" src="https://user-images.githubusercontent.com/50221806/122497488-45585300-cfa2-11eb-9f44-5d903c90d8e2.png">

### Option 5-12
5-7's full image.
<img width="505" alt="5-71" src="https://user-images.githubusercontent.com/50221806/122497500-49847080-cfa2-11eb-8e09-bd0fa3ce1cb6.png">

### Option 5-13
5-8's full image.
<img width="505" alt="5-70" src="https://user-images.githubusercontent.com/50221806/122497510-4db08e00-cfa2-11eb-80ed-7bbca06e661e.png">

### Option 5-14
5-9's full image.
<img width="505" alt="5-69" src="https://user-images.githubusercontent.com/50221806/122497521-52754200-cfa2-11eb-9763-ee9744dbfa40.png">

**Comment by juanis2112** [comment]
And the winner is... 5.11
