### ISSUE TITLE
Spyder Logo Voting

### ISSUE THREAD

**Issue by isabela-pf** [spyder-ide/ux-improvements#50]
We’ve been working and getting feedback on Spyder’s logo over at [spyder-ide/spyder #13181](https://github.com/spyder-ide/spyder/issues/13181), but now it’s time to vote! We’ll be using this issue as a voting platform.

A few things to note:
- Voting closes on June 4th
- Please only vote for one option
- Remember logos need to be used in a lot of different cases, so take note on the requested example uses on the last page of each PDF and any others you may think of on your own.

We have two similar options to choose between, numbers taken from the original issue. They are in PDF form since it was requested for easier side-by-side viewing.

## 3-16 Square
[3-16-square.pdf](https://github.com/spyder-ide/ux-improvements/files/6549843/3-16-square.pdf)

**To vote for 3-16 Square, react to this post with a 😄**

## 3-17
[3-17.pdf](https://github.com/spyder-ide/ux-improvements/files/6549863/3-17.pdf)

**To vote for 3-17, react to this post with a 🚀**

Thanks for taking the time to be a part of the Spyder community and voting!

**Comment by juanis2112** [comment]
Thanks Isabela. @spyder-ide/core-developers @spyder-ide/junior-developers please vote.

**Comment by jnsebgosselin** [comment]
This looks great, good job!

**Comment by karlos124c** [comment]
I prefer the current logo:

in my personal view a more "comic like" approach could be considered...

i like the current logo..probably a more aggressive python or web would be another idea to consider

**Comment by juanis2112** [comment]
We would also like to invite our previous contributors to vote! 
@PierreRaybaut @rlaverde @blink1073 @SylvainCorlay @techtonik @ok97465 @mariacamilarg @dhoegh @csabella @metalogical @jedludlow @Nodd @Prikers @orcargus @malliwi88 @timhoffm @Khalilsqu @dougthor42 @skjerns @definite-purple @hengin @arielrossanigo @thepycoder @pwoosam @gepcel @sohnishi @bnavigator @yuvipanda @jgoutin @fangohr @dpturibio @hugobuddel @AfzalivE @Qlogin @manipuladordedados @larsoner @ElieGouzien @flying-sheep @grantcathew @alexschw @jansorg @Keou007 @leportella @davidovitch @noyava @martindurant @athompson673  @jonnyhsu @suokunlong @alexanderdeweert @minrk @burrbull @takluyver @eendebakpt @cjrh @aglotero @rahmedov @mikofski @ShenggaoZhu @sehnem @MatthieuDartiailh @randyheydon @thewhitetulip @davidxbuck @akdor1154 @guisvail @arteagac @PanderMusubi @akwasigroch @randallpittman @its-dhung @spillz @michalgregor @igotdsm @vasily-smirnov @kingmo888 @@emanspeaks @ehabkost @DStauffman @tovogt @MaxGyver83 @lukruh @avylove @GKosiba @rotemgb

**Comment by juanis2112** [comment]
@minrk @burrbull @takluyver @eendebakpt @cjrh @aglotero @rahmedov @mikofski @ShenggaoZhu @sehnem @MatthieuDartiailh @randyheydon @thewhitetulip @davidxbuck @akdor1154 @guisvail @arteagac @PanderMusubi @akwasigroch @randallpittman @its-dhung @spillz @michalgregor @igotdsm @vasily-smirnov @kingmo888 @emanspeaks @ehabkost @DStauffman @tovogt @MaxGyver83 @lukruh @avylove @GKosiba @rotemgb

**Comment by yuvipanda** [comment]
I really appreciate the ping, @juanis2112! 

Others, to keep the comments here clean, please just react to this comment to show appreciation for @juanis2112's pings rather than add more comments :)

**Comment by techtonik** [comment]
I don't know how to give feedback to flesh people, so I hope you can setup your sense filters properly. I suppose voters are only those who support the logo change, and I've just been tagged, so I don't know why and when a consensus to change the logo was reached and just take this 15 minutes to throw in my bikeshedding opinion.

For some reason I hate new logo change. Maybe not as much as a hated button style change. As a hater I usually can not explain my feelings, but I agree with what is summarized here about Audacity https://www.youtube.com/watch?v=RMWNvwLiXIQ and instead of giving the exact timing, let you watch it whole.

To make a decision, I would prefer to see a page of Spyder logo history. I thought that it was green something, but maybe it was just a loading screen. Straight lines for everything Pythonic look extremely out of place. Straight lines web is ugly. I don't associate the project I picked up back then on Google Code with this combination of stained blood colors and almost corporate atrocity.

**Comment by juanis2112** [comment]
Hi everyone, quick reminder: Today is the last day for voting so please vote if you haven't!

**Comment by vasily-smirnov** [comment]
As for me, I like the current logo - it is quite nice and recognizable.
If change is really needed, 3-16 is acceptable and feels better than other candidates.

**Comment by karlos124c** [comment]
I vote for the current logo, revamped or a bit edgier..for the python on the spyder web

**Comment by karlos124c** [comment]
> 
> 
> As for me, I like the current logo - it is quite nice and recognizable.
> If change is really needed, 3-16 is acceptable and feels better than other candidates.

its true, is more recognizable and original

**Comment by ccordoba12** [comment]
Sorry guys but the decision to revamp our logo among the options @isabela-pf posted is already taken. So I blocked this issue to not spam all our previous contributors with further comments.

**Comment by PierreRaybaut** [comment]
If it was me, I would have kept the original logo - not only because it is now well known, but also since I put a lot of my heart in the logo (my wife helped me design it), as much as in the original Spyder's code base. Besides, the logo itself was initially designed together with the name itself, Spyder: the logo is as much significant to me as the name itself.

Sorry for reacting a bit late to this, but as much as I'm fond of all the work done since my retirement of the project, I'm not convinced by this change...

**Comment by ccordoba12** [comment]
Hey @PierreRaybaut, I understand this decision is hard for you to accept. Your logo has been the brand of the project and served it well for a long time, more than a decade actually, and several years after your retirement. So the decision to change it was not taken lightly by the team, believe me.

However, at this point we feel that we need a new face for the new decade and also a change to go with all the UI improvements we implemented in 5.0.

Thanks for understanding.

**Comment by SylvainCorlay** [comment]
I really like the designs proposed by @isabela-pf!

On the decision to change logo, changing a well-recognized design is an important decision. When we look at the evolution of the logos of most recognizable brands, we see that change happens very slowly, with subtle updates over time (Renault, Apple, McDonalds). Radical changes are rare,because of the cost of losing a well-recognized brand.

I would favor keeping the historical logo, or maybe work on subtle evolution of it while keeping it's general aspect.

**Comment by PierreRaybaut** [comment]
Hey @ccordoba12,
I think @SylvainCorlay's point of view is very interesting: I fully understand the need to change the logo, for modernizing it along with the rest of the UI. But a subtle change would indeed have been more appropriate to avoid losing Spyder's spirit. And I certainly would not be opposed to such change.

**Comment by ccordoba12** [comment]
This will be my second to last message before locking this issue (to not keep spamming a lot of people). If you want to keep discussing about it, please post your comments on issue spyder-ide/spyder#13181.

----

About @SylvainCorlay's comments:

> I really like the designs proposed by @isabela-pf!

I'm really glad to hear it!

> Radical changes are rare,because of the cost of losing a well-recognized brand.

Agreed, and we tried to maintain the spirit of the logo as much as we could. I don't think this is radical departure, but a different take on the same subject. In a way, one could say this is similar to a very famous recent example of logo redesign: Instagram. They also kept the recognizable elements of their logo but proposed a necessary overhaul. A lot of people complained loudly at first, but it was accepted at the end.

> I would favor keeping the historical logo, or maybe work on subtle evolution of it while keeping it's general aspect.

Thanks for your input Sylvain. We went through a lot of iterations (see spyder-ide/spyder#13181) and dozens of hours of discussions and this the best we could come up with. Unfortunately, the current logo has some issues that don't allow us to slightly improve it. @isabela-pf can explain you about them on spyder-ide/spyder#13181, if you're interested.

----

About @PierreRaybaut's comment:

> a subtle change would indeed have been more appropriate to avoid losing Spyder's spirit. And I certainly would not be opposed to such change.

Pierre, as you can see on spyder-ide/spyder#13181, (i) we've been discussing about a new logo for almost a year now; and (ii) the finally selected logo is a refinement of one proposed by one of our new (and most prolific) current contributors, and most of the active core team endorsed it. So I think the time for change has come.

**Comment by ccordoba12** [comment]
On behalf of the Spyder team, I want to thank everyone that voted to select our new logo. Thanks a lot for your support! We hope you'll like to see it in your desktops after Spyder 5.1.0 is released in July.

Finally, I'd like to thank @isabela-pf deeply for her work on this and her patience. You did a great job Isabela!

**Comment by PierreRaybaut** [comment]
Hey @ccordoba12 , you wrote "the current logo has some issues": how outrageous, I don't see any design flaw 😁 (couldn't resist, sorry 🙂).

I fully understand the motivation and I think that @isabela-pf has undoubtedly done an incredible work. 👏

I promise that, when I install Spyder v5.1, I will not change back the launch shortcut icon to the old logo. 😉

Sorry for spamming everyone but I still feel at home when it comes to Spyder...
